//app
export const HIDE_MAP_LOADING = 'HIDE_MAP_LOADING';
export const SHOW_MAP_LOADING = 'SHOW_MAP_LOADING';
export const SHOW_FLASH_MESSAGE = 'SHOW_FLASH_MESSAGE';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const SET_LANGUAGE = 'SET_LANGUAGE';

//map
export const SET_ZOOM_LEVEL = 'SET_ZOOM_LEVEL';
export const SET_MY_REGION = 'SET_MY_REGION';
export const SET_DEFAULT_REGION = 'SET_DEFAULT_REGION';
export const SET_ORIGINAL_DATA = 'SET_ORIGINAL_DATA';
export const SET_DISPLAY_DATA = 'SET_DISPLAY_DATA';
//DIRECTION
export const SET_ROUTE_DESTINATION = 'SET_ROUTE_DESTINATION';
export const SET_ROUTE_DESTINATION_LOADING = 'SET_ROUTE_DESTINATION_LOADING';
// ADDED
export const MAP_DRAG_STARTED = 'DRAG_STARTED';
export const MARKER_SELECTED = 'MARKER_SELECTED';
export const MAP_DRAG_ENDED = 'DRAG_ENDED';
export const MAP_REGION_SELECTED = 'MAP_REGION_SELECTED'; //cardPressed or myLocation pressed
export const MAP_PRESSED = 'MAP_PRESSED';
export const SET_MAP_MODE = 'SET_MAP_MODE';
export const MAP_ANIMATION_STARTED = 'ANIMATION_STARTED';
export const MAP_ANIMATION_ENDED = 'ANIMATION_ENDED';

//search
export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD';
export const SET_SEARCH_STATUS = 'SET_SEARCH_STATUS';
export const SET_SEARCH_RESULT_TEXT = 'SET_SEARCH_RESULT_TEXT';
export const SET_SEARCH_RESULT_LIST = 'SET_SEARCH_RESULT_LIST';
export const SET_SEARCH_FOCUS = 'SET_SEARCH_FOCUS';
//ADD
export const ACTIVATE_SEARCH = 'ACTIVATE_SEARCH';
export const DEACTIVATE_SEARCH = 'DEACTIVATE_SEARCH';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_REQUEST_SUCCESS = 'SEARCH_REQUEST_SUCCESS';
export const SEARCH_REQUEST_NOT_FOUND = 'SEARCH_REQUEST_NOT_FOUND';
export const RESET_SEARCH = 'RESET_SEARCH';

//draggable
export const SHOW_LIST = 'SHOW_LIST';
export const HIDE_LIST = 'HIDE_LIST';
export const TOGGLE_LIST = 'TOGGLE_LIST';

//scrollView
export const SCROLL_TO = 'SCROLL_TO';

//description
export const SHOW_DESCRIPTION = 'SHOW_DESCRIPTION';
export const HIDE_DESCRIPTION = 'HIDE_DESCRIPTION';
