//app
export const HIDE_MAP_LOADING = 'HIDE_MAP_LOADING';
export const SHOW_MAP_LOADING = 'SHOW_MAP_LOADING';
export const SHOW_FLASH_MESSAGE = 'SHOW_FLASH_MESSAGE';

//map
export const SET_MY_REGION = 'SET_MY_REGION';
export const SET_DEFAULT_REGION = 'SET_DEFAULT_REGION';
export const SET_ORIGINAL_DATA = 'SET_ORIGINAL_DATA';
export const SET_DISPLAY_DATA = 'SET_DISPLAY_DATA';

//search
export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD';
export const SET_SEARCH_STATUS = 'SET_SEARCH_STATUS';
export const SET_SEARCH_RESULT_TEXT = 'SET_SEARCH_RESULT_TEXT';
export const SET_SEARCH_RESULT_LIST = 'SET_SEARCH_RESULT_LIST';

//draggable
export const SHOW_DRAGGABLE_PANEL = 'SHOW_DRAGGABLE_PANEL';
export const HIDE_DRAGGABLE_PANEL = 'HIDE_DRAGGABLE_PANEL';

//scrollView
export const SCROLL_TO = 'SCROLL_TO';
